# Generated by Django 4.1.3 on 2022-11-16 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0002_album_artist_genre_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AddField(
            model_name='genre',
            name='song_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jams.song'),
            preserve_default=False,
        ),
    ]
