# Generated by Django 4.1.3 on 2022-11-16 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0003_genre_name_genre_song_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jams.genre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AddField(
            model_name='album',
            name='release',
            field=models.IntegerField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='song_name',
            field=models.ManyToManyField(to='jams.song'),
        ),
    ]
