# Generated by Django 4.1.3 on 2022-11-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0004_album_genre_album_name_album_release_album_song_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AddField(
            model_name='playlist',
            name='song_name',
            field=models.ManyToManyField(to='jams.song'),
        ),
    ]
