# Generated by Django 4.1.3 on 2022-11-16 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0005_playlist_name_playlist_song_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='about',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jams.genre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='name',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(to='jams.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='number_of_plays',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
