# Generated by Django 4.1.3 on 2022-11-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0006_artist_about_artist_genre_artist_name_song_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(null=True, to='jams.artist'),
        ),
    ]
