# Generated by Django 4.1.3 on 2022-11-16 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0010_remove_artist_genre_genre_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='artist',
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jams.genre'),
        ),
    ]
