# Generated by Django 4.1.3 on 2022-11-16 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0012_remove_genre_song_name_song_song_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_name',
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jams.genre'),
        ),
    ]
