# Generated by Django 4.1.3 on 2022-11-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0013_remove_song_song_name_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(blank=True, null=True, related_name='artist', to='jams.artist'),
        ),
    ]
